name: Commit message lint

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  commitlint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Lint commits in PR
        uses: wagoid/commitlint-github-action@v4
        with:
          configFile: commitlint.config.js
